LoginSignup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Users/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',  views.index, name='index'),
    path('register/', views.usercreation, name='register'),
    path('accounts/login/', views.userpage, name='userpage'),
    path('accounts/login/userpage/', views.userauthentication, name='userauthentication'),
    path('postcategory',views.postcategory,name='postcategory'),
    path('postquestion',views.postquestion,name='postquestion'),
    path('viewquestions',views.viewquestions, name='viewquestions'),
    path('viewhistory/', views.viewhistory, name='viewhistory'),
    path('userhistory/<int:pk>/', views.userhistory, name='userhistory'),
    path('updateprofile',views.updateprofile, name = 'updateprofile'),
    path('viewcategory/', views.viewcategory,name= 'viewcategory'),
    path('takequiz/<int:pk>/',views.takequiz, name='takequiz'),
    path('result/<int:pk>/', views.result, name='result'),
    path('editquestion/<int:pk>/', views.editquestions, name='editquestion'),
    path('editcatogiries/<int:pk>/', views.editcategories, name='editcategory'),
    path('success/',views.success, name='success'),
    path('forgot/',views.forgot, name='forgot'),
    path('questionlist/', views.QuestionList.as_view(), name='questionlist'),
    path('questiondetal/<int:pk>/',views.QuestionDetail.as_view(),name='questiondetail'),
    path('viewanswers/',views.viewanswers,name = 'viewanswers')

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class QuizAppUser(AbstractUser):
    profile_image = models.ImageField(upload_to='media/',default='')


class Category(models.Model):
    name = models.CharField(max_length=30,blank=False,null=True)

    def __str__(self):
        return self.name


class Question(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=None, null=True)
    question = models.CharField(max_length=255)

    def __str__(self):
        return self.question


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.CharField(max_length=50)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return self.answer


class Quiz(models.Model):
    owner = models.ForeignKey(QuizAppUser, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    score = models.CharField(max_length=10, null=True)


class Guess(models.Model):
    submitted_by = models.ForeignKey(QuizAppUser, on_delete=models.CASCADE)
    answered_question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_given = models.ForeignKey(Choice, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)


class Update(models.Model):
    first_name=models.CharField(max_length=32)
    last_name=models.CharField(max_length=30)
    user_name=models.CharField(max_length=30)
    email = models.EmailField()

Users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import QuizAppUser
from django import forms


class RegistrationForm(UserCreationForm):
        class Meta:
                model = QuizAppUser
                fields = ['username','email','first_name','last_name','profile_image']

Users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import RegistrationForm
from django.contrib.auth.forms import AuthenticationForm
from .models import Question, Choice, QuizAppUser,Category,Quiz,Guess,Update
from django.contrib import messages
from django.views import generic
from django.urls import reverse


# Create your views here.

def index(request):
    return render(request, 'index.html')


def usercreation(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            request.session['user'] = username
            return redirect('userauthentication')

    else:
        form = RegistrationForm()

    return render(request, 'registration/register2.html', {'form': form})


def userpage(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                request.session['user'] = username
                return redirect('userauthentication')
            messages.add_message(request, messages.INFO, 'User is Not Active.')
            return redirect('userpage')
        messages.add_message(request, messages.INFO, 'Please Check Your Login Credentials.')
        return redirect('userpage')

    else:
        form = AuthenticationForm()
        return render(request, 'registration/login.html', {'form': form})


def userauthentication(request):
    if request.session.has_key('user'):
        username = request.session['user']
        user = QuizAppUser.objects.get(username=username)
        if user.is_staff == True:
            return render(request, 'AdminPage.html')
        categories = Category.objects.all()
        return render(request, 'userpage.html', {'categories': categories})
    return redirect('userpage')


def postcategory(request):
    if request.session.has_key('user'):
        if request.method == 'POST':
            category = request.POST['category']
            new_category = Category(name=category)
            new_category.save()
            messages.add_message(request, messages.INFO, 'Category Added Successfully.')
            return redirect('postcategory')
        return render(request, 'PostCategory.html')
    return redirect('userpage')


def postquestion(request):
    if request.session.has_key('user'):
        if request.method == 'POST':
            que = request.POST['question']
            category = request.POST['category']
            option1 = request.POST['option1']
            option2 = request.POST['option2']
            option3 = request.POST['option3']
            option4 = request.POST['option4']
            category_id = Category.objects.get(name=category)
            question = Question.objects.create(category=category_id, question=que)
            try:
                option1_check = request.POST['check_option1']
                choice_1 = Choice.objects.create(question=question, answer=option1, correct=option1_check)
            except:
                choice_1 = Choice.objects.create(question=question, answer=option1)
            try:
                option2_check = request.POST['check_option2']
                choice_2 = Choice.objects.create(question=question, answer=option2, correct=option2_check)
            except:
                choice_2 = Choice.objects.create(question=question, answer=option2)
            try:
                option3_check = request.POST['check_option3']
                choice_3 = Choice.objects.create(question=question, answer=option3, correct=option3_check)
            except:
                choice_3 = Choice.objects.create(question=question, answer=option3)
            try:
                option4_check = request.POST['check_option4']
                choice_3 = Choice.objects.create(question=question, answer=option4, correct=option4_check)
            except:
                choice_3 = Choice.objects.create(question=question, answer=option4)

            messages.add_message(request, messages.INFO, 'Question Posted Successfully.')
            return redirect('postquestion')
        categories = Category.objects.all()
        return render(request, 'postquestion.html', {'categories': categories})
    return redirect('userpage')


def viewquestions(request):
    if request.session.has_key('user'):
        categories = Category.objects.all()
        return render(request, 'viewquestions.html', {'categories': categories})
    return redirect('userpage')


def viewhistory(request):
    if request.session.has_key('user'):
        if request.method == 'POST':
            pass
        quizs = Quiz.objects.all()
        return render(request, 'viewhistory.html', {'quizs': quizs})
    return redirect('usepage')


def userhistory(request,pk):
    if request.session.has_key('user'):
        if request.method == 'POST':
            pass
        quizs = Quiz.objects.filter(owner=pk)
        return render(request, 'userhistory.html', {'quizs': quizs})
    return redirect('usepage')


def viewcategory(request):
    if request.session.has_key('user'):
        if request.method == 'GET':
            categories = Category.objects.all()
            return render(request,'viewcategory.html',{'categories': categories})
    return redirect('usepage')

def takequiz(request, pk):
    if request.session.has_key('user'):
        category = Category.objects.get(pk=pk)
        questions = Question.objects.filter(category=category)
        return render(request, 'quiz.html', {'questions': questions, 'category': category})
    return redirect('userpage')


def result(request, pk):
    if request.session.has_key('user'):
        if request.method == 'POST':
            username = request.session['user']
            category = Category.objects.get(pk=pk)
            submitted_by = QuizAppUser.objects.get(username=username)
            quiztaken = Quiz(owner=submitted_by, category=category)
            quiztaken.save()
            question_count = Question.objects.filter(category=pk).count()
            for i in range(1, question_count + 1):
                question_id = request.POST['question' + str(i)]
                answered_question = Question.objects.get(id=question_id)
                choice_id = request.POST['check_option' + str(i)]
                answer_given = Choice.objects.get(id=choice_id)
                quiz = Guess(submitted_by=submitted_by, answer_given=answer_given, answered_question=answered_question,
                             quiz=quiztaken)
                quiz.save()

            score = 0
            guesses = Guess.objects.filter(submitted_by=submitted_by, quiz=quiztaken)
            for guess in guesses:
                if guess.answer_given.correct == True:
                    score += 1

            quiztaken.score = score
            quiztaken.save()

            return render(request, 'success.html', {'score': score, 'count': question_count})

    return redirect('userpage')


def success(request):
    pass


def editquestions(request, pk):
    if request.session.has_key('user'):
        if request.method == "POST":
            que = request.POST['question']

            question = Question.objects.get(id=pk)
            question.question = que
            question.save()

            choices = question.choice_set.all()

            for i in range(4):
                choice_id = choices[i].id
                obj = Choice.objects.get(pk=choice_id)
                obj.answer = request.POST['option' + str(i + 1)]
                try:
                    obj.correct = request.POST['check_option' + str(i + 1)]
                except:
                    obj.correct = False
                obj.save()

            return redirect('viewquestions')
        question = Question.objects.get(id=pk)
        choices = Choice.objects.filter(question=question)
        return render(request, 'editquestion.html', {'question': question, 'choices': choices})
    return redirect('userpage')


def editcategories(request,pk):
    if request.session.has_key('user'):
        if request.method == "POST":
            cat = request.POST['category']
            category = Category.objects.get(id=pk)
            category.name = cat
            category.save()
            return redirect('viewcategory')
        category = Category.objects.get(id=pk)
        return render(request, 'editcategory.html', {'category': category })
    return redirect('userpage')


def forgot(request):
    return render(request,'forgot.html')


def updateprofile(request):
    # if request.session.has_key('user'):
    #     if request.method == "POST":
    #         fname = request.POST['First name']
    #         lname = request.POST['Last name']
    #         uname = request.POST['User name']
    #         email = request.POST['Email Address']
    #         insert = models.QuizAppUser(First_Name=fname, Last_name=lname, User_name=uname, Email=email)
    #         insert.save()
    #         messages.add_message(request, messages.INFO,'Registration Successfully completed.')
    #         return redirect('login')
        return render(request, 'updateprofile.html')
    #return redirect('userpage')


def viewanswers(request):
    if request.session.has_key('user'):
        if request.method == "GET":
            return render(request,'viewanswers.html')
        return render(request,)
    return redirect('userpage')





class QuestionList(generic.ListView):
    template_name = 'questionlist.html'

    def get_queryset(self):
        return Question.objects.all()

Users/templates/AdminPage.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Index</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
</head>
<body>
	<nav class="navbar navbar-light bg-light">
  		<h2 class="navbar-brand mb-0 ml-4">Welcome to QuizApp</h2>
      <a href="/accounts/logout/" class="btn btn-primary">Logout</a>
	</nav>
	<div class="row m-4">

  <div class="card m-4" style="width: 18rem;">
    <div class="card-body">
    <h5 class="card-title">Add Category</h5>
    <p class="card-text">You Can Add new Category of a Quiz.</p>
    <a href="/postcategory" class="btn btn-primary">Add Category</a>
    </div>
  </div>
	
	<div class="card m-4" style="width: 18rem;">
  	<div class="card-body">
    <h5 class="card-title">Add Question</h5>
    <p class="card-text">You Can Add new Questions to Quiz Application Here.</p>
    <a href="/postquestion" class="btn btn-primary">Add Question</a>
  	</div>
	</div>
        <div class="card m-4" style="width: 18rem;">
  	<div class="card-body">
    <h5 class="card-title">View Questions</h5>
    <p class="card-text">You Can View the Questions that you have added.</p>
    <a href="/viewquestions" class="btn btn-primary">View Questions</a>
  	</div>
	</div>

	<div class="card m-4" style="width: 18rem;">
  	<div class="card-body">
    <h5 class="card-title">View History</h5>
    <p class="card-text">You can see the history of users here.</p>
    <a href="/viewhistory" class="btn btn-primary">View History</a>
  	</div>
	</div>
        <div class="card m-4" style="width: 18rem;">
  	<div class="card-body">
    <h5 class="card-title">View Category</h5>
    <p class="card-text">You can see the Posted Categorys here.</p>
    <a href="/viewcategory" class="btn btn-primary">View Category</a>
  	</div>
	</div>

	</div>



<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

Users/templates/PostCategory.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Post Category</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
</head>
<body>
	<nav class="navbar navbar-light bg-light">
  		<h2 class="navbar-brand mb-0 ml-4">Welcome to QuizApp Login</h2>
      <ul class="navbar-nav ml-auto">
        <ul class="navbar-nav">
            <li class="nav-item">
          <a class="btn btn-primary" href="/accounts/login/userpage/">Home <span class="sr-only">(current)</span></a>
        </li>
        </ul>
	</nav>
	<form method="POST" action="{% url 'postcategory' %}">
		{% csrf_token %}


		<div class="mt-5 pt-3">
    <div class="card offset-md-3 offset-sm-1 my-5 mt-5" style="max-width: 50rem;">
    <div class="card-header text-center light-blue darken-3 white-text ">
    <h4 class="card-title">Post Category</h4>
    {% if messages %}
                {% for msg in messages %}
                    <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{msg.message}}
                    </div>
                {% endfor %}
            {% endif %}
    </div>

   <div class="row m-3 ">
    <div class="col-6 offset-md-3">
      <div class="form-group">
        <label for="category">Category</label>
          <form> <input type="text" class="form-control"  id ="category" name="category" placeholder="Enter Your Category" required></form>
      </div>
    </div>
  </div>
    <div class="row align-items-center ml-3 mb-3">
<button type="submit" class="btn btn-primary offset-md-5">POST</button>
</div>
</form>

</div>
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>
</div>

Users/templates/editquestion.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Edit Question</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
</head>
<body>
	<nav class="navbar navbar-light bg-light">
  		<h2 class="navbar-brand mb-0 ml-4">Welcome to QuizApp</h2>
      <ul class="navbar-nav ml-auto">
        <ul class="navbar-nav">
            <li class="nav-item">
          <a class="btn btn-primary" href="/accounts/login/userpage/">Home <span class="sr-only">(current)</span></a>
        </li>
        </ul>
	</nav>
	<form method="POST" action="">
		{% csrf_token %}


		<div class="mt-5 pt-3">
    <div class="card offset-md-3 offset-sm-1 my-5 mt-5" style="max-width: 50rem;">
    <div class="card-header text-center light-blue darken-3 white-text ">
    <h4 class="card-title">Edit Question</h4>
    {% if messages %}
                {% for msg in messages %}
                    <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{msg.message}}
                    </div>
                {% endfor %}
            {% endif %}
    </div>

<div class="row m-2">
<div class="col-10">
  <div class="form-group">
    <label for="question">Question</label>
    <input type="text" class="form-control" id ="question" name="question" placeholder="Enter Your Question..?" value="{{ question.question }}">
  </div>
</div>
</div>
{% for choice in choices %}
  <div class="form-row align-items-center ml-3 mb-3">
    <div class="col-4 my-1">
      <input type="text" class="form-control"  name="option{{forloop.counter}}" placeholder="Option 1" value="{{ choice.answer }}">
    </div>
{#  <div class="col-auto my-1">#}
{#  <div class="form-group form-check">#}
{#      <input class="form-check-input" type="radio" name="exampleRadios" id="{{ choice.id }}" name="check_option{{forloop.counter}}" value="True"#}
{#       {% if choice.correct %} checked {% endif %} >#}
{#  <label class="form-check-label" for="exampleRadios2">#}
{#  </label>#}
{#  </div>#}
{#</div>#}
    <div class="col-auto my-1">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="{{choice.id}}" name="check_option{{forloop.counter}}" value="True"
        {% if choice.correct %} checked {% endif %} >
        <label class="form-check-label" for="autoSizingCheck2">
        </label>
      </div>
    </div>
  </div>
{% endfor %}

<div class="row align-items-center ml-3 mb-3">
<button type="submit" class="btn btn-primary offset-md-5">Save</button>
</div>
</form>

</div>
	</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>

</body>
</html>

Users/templates/forgot.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>ForgotPassword</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
</head>
<body>
<form method="POST" action="{% url 'login' %}">
	{% csrf_token %}

	<nav class="navbar navbar-light bg-light">
  		<h2 class="navbar-brand mb-0 ml-4">Welcome to QuizApp Login</h2>
      <ul class="navbar-nav ml-auto">
        <ul class="navbar-nav">
            <li class="nav-item">
          <a class="btn btn-primary" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        </ul>
	</nav>

	<div class="mt-5 pt-3">
    <div class="card offset-md-4 offset-sm-1 my-5 mt-5" style="max-width: 35rem;">
    <div class="card-header text-center light-blue darken-3 white-text ">
    <h4 class="card-title">Forgot Password ?</h4>
    <h6 class="card-title">Reset your password here</h6>
    {% if messages %}
                {% for msg in messages %}
                    <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{msg.message}}
                    </div>
                {% endfor %}
            {% endif %}
  <div class="form-group">
    <label for="exampleInputPassword1">NewPassword</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Enter NewPassword">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Conform</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Enter ConformPassword">
  </div>

{#  <button type="submit" class="btn btn-primary">Submit</button><br><br>#}
    <a href="/accounts/login/" class="btn btn-primary">Submit</a>
</form>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

Users/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Index</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
</head>
<body>
	<nav class="navbar navbar-light bg-light">
  		<h2 class="navbar-brand mb-0 ml-4">Welcome to QuizApp</h2>
	</nav>
	<div class="row m-4">
	
	<div class="card m-4" style="width: 18rem;">
  	<div class="card-body">
    <h5 class="card-title">User Login</h5>
    <p class="card-text">Existing Users Can Login Here.</p>
    <a href="/accounts/login/" class="btn btn-primary">Login</a>
  	</div>
	</div>

	<div class="card m-4" style="width: 18rem;">
  	<div class="card-body">
    <h5 class="card-title">New User...?</h5>
    <p class="card-text">New Users Can Register Here.</p>
    <a href="/register" class="btn btn-primary">Register</a>
  	</div>
	</div>

	<div class="card m-4" style="width: 18rem;">
  	<div class="card-body">
    <h5 class="card-title">Admin Login</h5>
    <p class="card-text">Admin Can Login Here.</p>
    <a href="/admin/" class="btn btn-primary">Login</a>
  	</div>
	</div>

	</div>

<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

Users/templates/postquestion.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Post Question</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
</head>
<body>
	<nav class="navbar navbar-light bg-light">
  		<h2 class="navbar-brand mb-0 ml-4">Welcome to QuizApp Login</h2>
      <ul class="navbar-nav ml-auto">
        <ul class="navbar-nav">
            <li class="nav-item">
          <a class="btn btn-primary" href="/accounts/login/userpage/">Home <span class="sr-only">(current)</span></a>
        </li>
        </ul>
	</nav>
	<form method="POST" action="{% url 'postquestion' %}">
		{% csrf_token %}


		<div class="mt-5 pt-3">
    <div class="card offset-md-3 offset-sm-1 my-5 mt-5" style="max-width: 50rem;">
    <div class="card-header text-center light-blue darken-3 white-text ">
    <h4 class="card-title">Post Question</h4>
    {% if messages %}
                {% for msg in messages %}
                    <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{msg.message}}
                    </div>
                {% endfor %}
            {% endif %}
    </div>

<div class="row m-2">
<div class="col-10">
  <div class="form-group">
    <label for="category">Category</label>
      <select id="category" class="form-control" name="category">
        <option selected>Choose...</option>
        {% for category in categories %}
        <option value="{{category}}">{{category}}</option>
        {% endfor %}
      </select>
  </div>
</div>
</div>

<div class="row m-2">
<div class="col-10">
  <div class="form-group">
    <label for="question">Question</label>
    <input type="text" class="form-control"  id ="question" name="question" placeholder="Enter Your Question..?">
  </div>
</div>
</div>


  <div class="form-row align-items-center ml-3 mb-3">
    <div class="col-4 my-1">
      <input type="text" class="form-control"  name="option1" placeholder="Option 1">
    </div>
    <div class="col-auto my-1">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="autoSizingCheck2" name="check_option1" value="True">
        <label class="form-check-label" for="autoSizingCheck2">
        </label>
      </div>
    </div>
  </div>

  <div class="form-row align-items-center ml-3 mb-3">
    <div class="col-4 my-1">
      <input type="text" class="form-control"  name="option2" placeholder="Option 2">
    </div>
    <div class="col-auto my-1">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="autoSizingCheck2" name="check_option2" value="True">
        <label class="form-check-label" for="autoSizingCheck2">
        </label>
      </div>
    </div>
  </div>

  <div class="form-row align-items-center ml-3 mb-3">
    <div class="col-4 my-1">
      <input type="text" class="form-control"  name="option3" placeholder="Option 3">
    </div>
    <div class="col-auto my-1">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="autoSizingCheck2" name="check_option3" value="True">
        <label class="form-check-label" for="autoSizingCheck2">
        </label>
      </div>
    </div>
  </div>

  <div class="form-row align-items-center ml-3 mb-3">
    <div class="col-4 my-1">
      <input type="text" class="form-control"  name="option4" placeholder="Option 4">
    </div>
    <div class="col-auto my-1">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="autoSizingCheck2" name="check_option4" value="True">
        <label class="form-check-label" for="autoSizingCheck2">
        </label>
      </div>
    </div>
  </div>
<div class="row align-items-center ml-3 mb-3">
<button type="submit" class="btn btn-primary offset-md-5">POST</button>
</div>
</form>

</div>
	</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

Users/templates/questiondetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{questiondetails.question}}<br>
{% for choice in questiondetails.choice_set.all %}
{{choice}}<br>
{% endfor %}
</body>
</html>

Users/templates/viewquestions.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Questions Page</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
</head>
<body>

	<nav class="navbar navbar-light bg-light">
  		<h2 class="navbar-brand mb-0 ml-4">Welcome to QuizApp</h2>
      <ul class="navbar-nav ml-auto">
        <ul class="navbar-nav">
            <li class="nav-item">
          <a class="btn btn-primary" href="/accounts/login/userpage/">Home <span class="sr-only">(current)</span></a>
        </li>
        </ul>
	</nav>
  {% for category in categories %}

	<table class="table table-striped col-4 table-bordered m-4">
  <thead>
    <tr>
      <th class="text-center" colspan="3">{{category}}</th>
    </tr>
    <tr>
      <th scope="col">S.No</th>
      <th scope="col">Question</th>
      <th scope="col">Edit Question</th>
    </tr>
  </thead>
  <tbody>
    {% for question in category.question_set.all %}
    <tr>
      <th scope="row">{{forloop.counter}}.</th>
      <td>{{question}}</td>
      <td><a class="btn btn-secondary" href="{% url 'editquestion' question.id %}">Edit</a></td>
    </tr>
   {% endfor %}
</tbody>
</table>
{% endfor %}

</body>
</html>